// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/action/logout": {
    params: {};
  };
  "/action/set-theme": {
    params: {};
  };
  "/projects": {
    params: {};
  };
  "/projects/new": {
    params: {};
  };
  "/projects/:projectId": {
    params: {
      "projectId": string;
    };
  };
  "/projects/:projectId/analytics": {
    params: {
      "projectId": string;
    };
  };
  "/projects/:projectId/board": {
    params: {
      "projectId": string;
    };
  };
  "/projects/:projectId/board/issue/new": {
    params: {
      "projectId": string;
    };
  };
  "/projects/:projectId/board/issue/:issueId": {
    params: {
      "projectId": string;
      "issueId": string;
    };
  };
  "/projects/:projectId/server-error": {
    params: {
      "projectId": string;
    };
  };
  "/projects/:projectId/*": {
    params: {
      "projectId": string;
      "*": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/action/logout" | "/action/set-theme" | "/projects" | "/projects/new" | "/projects/:projectId" | "/projects/:projectId/analytics" | "/projects/:projectId/board" | "/projects/:projectId/board/issue/new" | "/projects/:projectId/board/issue/:issueId" | "/projects/:projectId/server-error" | "/projects/:projectId/*" | "/*";
  };
  "routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/action/logout.tsx": {
    id: "routes/action/logout";
    page: "/action/logout";
  };
  "routes/action/set-theme.tsx": {
    id: "routes/action/set-theme";
    page: "/action/set-theme";
  };
  "routes/__main.tsx": {
    id: "routes/__main";
    page: "/projects" | "/projects/new" | "/projects/:projectId" | "/projects/:projectId/analytics" | "/projects/:projectId/board" | "/projects/:projectId/board/issue/new" | "/projects/:projectId/board/issue/:issueId" | "/projects/:projectId/server-error" | "/projects/:projectId/*";
  };
  "routes/__main/projects.tsx": {
    id: "routes/__main/projects";
    page: "/projects" | "/projects/new";
  };
  "routes/__main/projects/new.tsx": {
    id: "routes/__main/projects/new";
    page: "/projects/new";
  };
  "routes/__main/projects.$projectId.tsx": {
    id: "routes/__main/projects.$projectId";
    page: "/projects/:projectId" | "/projects/:projectId/analytics" | "/projects/:projectId/board" | "/projects/:projectId/board/issue/new" | "/projects/:projectId/board/issue/:issueId" | "/projects/:projectId/server-error" | "/projects/:projectId/*";
  };
  "routes/__main/projects.$projectId/analytics.tsx": {
    id: "routes/__main/projects.$projectId/analytics";
    page: "/projects/:projectId/analytics";
  };
  "routes/__main/projects.$projectId/board.tsx": {
    id: "routes/__main/projects.$projectId/board";
    page: "/projects/:projectId/board" | "/projects/:projectId/board/issue/new" | "/projects/:projectId/board/issue/:issueId";
  };
  "routes/__main/projects.$projectId/board/issue/new.tsx": {
    id: "routes/__main/projects.$projectId/board/issue/new";
    page: "/projects/:projectId/board/issue/new";
  };
  "routes/__main/projects.$projectId/board/issue/$issueId.tsx": {
    id: "routes/__main/projects.$projectId/board/issue/$issueId";
    page: "/projects/:projectId/board/issue/:issueId";
  };
  "routes/__main/projects.$projectId/server-error.tsx": {
    id: "routes/__main/projects.$projectId/server-error";
    page: "/projects/:projectId/server-error";
  };
  "routes/__main/projects.$projectId/$.tsx": {
    id: "routes/__main/projects.$projectId/$";
    page: "/projects/:projectId/*";
  };
  "routes/404.tsx": {
    id: "routes/404";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "routes/index": typeof import("./src/app/routes/index.tsx");
  "routes/login": typeof import("./src/app/routes/login.tsx");
  "routes/action/logout": typeof import("./src/app/routes/action/logout.tsx");
  "routes/action/set-theme": typeof import("./src/app/routes/action/set-theme.tsx");
  "routes/__main": typeof import("./src/app/routes/__main.tsx");
  "routes/__main/projects": typeof import("./src/app/routes/__main/projects.tsx");
  "routes/__main/projects/new": typeof import("./src/app/routes/__main/projects/new.tsx");
  "routes/__main/projects.$projectId": typeof import("./src/app/routes/__main/projects.$projectId.tsx");
  "routes/__main/projects.$projectId/analytics": typeof import("./src/app/routes/__main/projects.$projectId/analytics.tsx");
  "routes/__main/projects.$projectId/board": typeof import("./src/app/routes/__main/projects.$projectId/board.tsx");
  "routes/__main/projects.$projectId/board/issue/new": typeof import("./src/app/routes/__main/projects.$projectId/board/issue/new.tsx");
  "routes/__main/projects.$projectId/board/issue/$issueId": typeof import("./src/app/routes/__main/projects.$projectId/board/issue/$issueId.tsx");
  "routes/__main/projects.$projectId/server-error": typeof import("./src/app/routes/__main/projects.$projectId/server-error.tsx");
  "routes/__main/projects.$projectId/$": typeof import("./src/app/routes/__main/projects.$projectId/$.tsx");
  "routes/404": typeof import("./src/app/routes/404.tsx");
};