import { User } from "@domain/user";
import { Activity } from "./activity";

const HOUR = 60 * 60 * 1000;
const DAY = 24 * HOUR;

/**
 * Timestamps are relative to a single reference "now" so the timeline always
 * has fresh Today / Yesterday / Last Week buckets whenever it renders.
 */
const now = Date.now();
const hoursAgo = (hours: number): number => now - hours * HOUR;
const daysAgo = (days: number, hours = 0): number => now - days * DAY - hours * HOUR;

export const activityUsersMock: User[] = [
  { id: "u-john", name: "John Doe", color: "#dae3f9" },
  { id: "u-sarah", name: "Sarah Johnson", color: "#f9dae8" },
  { id: "u-mike", name: "Mike Chen", color: "#d9f2e6" },
  { id: "u-emma", name: "Emma Davis", color: "#f6e6c4" },
  { id: "u-tom", name: "Tom Wilson", color: "#e2dbf7" },
  { id: "u-priya", name: "Priya Nair", color: "#cdeef7" },
];

const [john, sarah, mike, emma, tom, priya] = activityUsersMock;

export const activitiesMock: Activity[] = [
  {
    id: "act-1",
    type: "commit",
    user: john,
    timestamp: hoursAgo(2),
    description: "Fixed authentication bug in login component",
    commit: {
      message: "Fixed authentication bug in login component",
      hash: "a1b2c3d",
      branch: "feature/auth-fix",
      additions: 125,
      deletions: 43,
      files: [
        { path: "src/pages/Login/Login.tsx", additions: 48, deletions: 12 },
        { path: "src/pages/Login/useLogin.ts", additions: 32, deletions: 15 },
        { path: "src/api/auth.ts", additions: 24, deletions: 9 },
        { path: "src/utils/token.ts", additions: 16, deletions: 4 },
        { path: "src/pages/Login/Login.test.tsx", additions: 5, deletions: 3 },
      ],
    },
  },
  {
    id: "act-2",
    type: "comment",
    user: sarah,
    timestamp: hoursAgo(3),
    description: "Commented on Login.tsx",
    comment: {
      target: "Login.tsx",
      line: 45,
      text: "The token refresh call here fires before the session is hydrated, so the first render still shows the guest state. Can we move it into the auth provider so it runs once and the whole tree gets the resolved session at the same time?",
      replies: [
        {
          author: "John Doe",
          text: "Good catch — moving it into the provider now.",
          timestamp: hoursAgo(2.5),
        },
        {
          author: "Mike Chen",
          text: "Let's add a test for the guest-state flash too.",
          timestamp: hoursAgo(2.2),
        },
      ],
    },
  },
  {
    id: "act-3",
    type: "task",
    user: mike,
    timestamp: hoursAgo(5),
    description: "Completed Update authentication documentation",
    task: {
      key: "TASK-123",
      title: "Update authentication documentation",
      action: "completed",
      status: "completed",
      priority: "medium",
      assignee: "Mike Chen",
      dueDate: hoursAgo(5),
    },
  },
  {
    id: "act-4",
    type: "commit",
    user: sarah,
    timestamp: hoursAgo(6),
    description: "Extract session provider from login view",
    commit: {
      message: "Extract session provider from login view",
      hash: "b2c3d4e",
      branch: "feature/auth-fix",
      additions: 87,
      deletions: 54,
      files: [
        { path: "src/providers/SessionProvider.tsx", additions: 61, deletions: 0 },
        { path: "src/pages/Login/Login.tsx", additions: 12, deletions: 41 },
        { path: "src/app/root.tsx", additions: 14, deletions: 13 },
      ],
    },
  },
  {
    id: "act-5",
    type: "comment",
    user: priya,
    timestamp: hoursAgo(7),
    description: "Commented on SessionProvider.tsx",
    comment: {
      target: "SessionProvider.tsx",
      line: 22,
      text: "Nice cleanup. One thing: the provider swallows the error from the refresh call, so a revoked token looks identical to a logged-out user. Surfacing it would let the banner explain what happened.",
      replies: [
        {
          author: "Sarah Johnson",
          text: "Adding an error branch in the next commit.",
          timestamp: hoursAgo(6.4),
        },
      ],
    },
  },
  {
    id: "act-6",
    type: "task",
    user: emma,
    timestamp: hoursAgo(8),
    description: "Updated Audit login error states",
    task: {
      key: "TASK-140",
      title: "Audit login error states",
      action: "updated",
      status: "in-progress",
      priority: "high",
      assignee: "Emma Davis",
      dueDate: daysAgo(-2),
    },
  },
  {
    id: "act-7",
    type: "file",
    user: tom,
    timestamp: hoursAgo(9),
    description: "Created ActivityFeed.tsx",
    file: {
      operation: "created",
      path: "src/components/ActivityFeed/ActivityFeed.tsx",
      size: "4.1 KB",
    },
  },
  {
    id: "act-8",
    type: "settings",
    user: emma,
    timestamp: hoursAgo(10),
    description: "Changed Feature Flag: activity-timeline",
    settings: {
      name: "Feature Flag: activity-timeline",
      before: "Disabled",
      after: "Enabled",
      scope: "Shared-UI",
    },
  },
  {
    id: "act-9",
    type: "commit",
    user: john,
    timestamp: hoursAgo(11),
    description: "Add error branch to session refresh",
    commit: {
      message: "Add error branch to session refresh",
      hash: "c3d4e5f",
      branch: "feature/auth-fix",
      additions: 44,
      deletions: 8,
      files: [
        { path: "src/providers/SessionProvider.tsx", additions: 29, deletions: 5 },
        { path: "src/components/Banner/Banner.tsx", additions: 15, deletions: 3 },
      ],
    },
  },
  {
    id: "act-10",
    type: "user",
    user: priya,
    timestamp: hoursAgo(12),
    description: "Priya Nair was assigned as reviewer",
    userEvent: { action: "assigned as reviewer on feature/auth-fix" },
  },
  {
    id: "act-11",
    type: "commit",
    user: mike,
    timestamp: daysAgo(1, 1),
    description: "Split board column into presentational parts",
    commit: {
      message: "Split board column into presentational parts",
      hash: "d4e5f60",
      branch: "refactor/board-columns",
      additions: 168,
      deletions: 132,
      files: [
        { path: "src/board/Column.tsx", additions: 54, deletions: 88 },
        { path: "src/board/ColumnHeader.tsx", additions: 62, deletions: 0 },
        { path: "src/board/ColumnBody.tsx", additions: 52, deletions: 44 },
      ],
    },
  },
  {
    id: "act-12",
    type: "settings",
    user: emma,
    timestamp: daysAgo(1, 2),
    description: "Changed Feature Flag: dark-mode",
    settings: {
      name: "Feature Flag: dark-mode",
      before: "Disabled",
      after: "Enabled",
      scope: "Shared-UI",
    },
  },
  {
    id: "act-13",
    type: "user",
    user: tom,
    timestamp: daysAgo(1, 3),
    description: "Tom Wilson joined the project",
    userEvent: { action: "joined the project" },
  },
  {
    id: "act-14",
    type: "comment",
    user: john,
    timestamp: daysAgo(1, 4),
    description: "Commented on Column.tsx",
    comment: {
      target: "Column.tsx",
      line: 118,
      text: "The drop handler still recalculates the whole ordering array on every hover event. With 200 cards that's noticeable — memoizing on the dragged id should be enough.",
      replies: [
        {
          author: "Mike Chen",
          text: "Agreed, I'll memoize it.",
          timestamp: daysAgo(1, 3.4),
        },
      ],
    },
  },
  {
    id: "act-15",
    type: "task",
    user: priya,
    timestamp: daysAgo(1, 5),
    description: "Created Memoize board drop handler",
    task: {
      key: "TASK-141",
      title: "Memoize board drop handler",
      action: "created",
      status: "created",
      priority: "medium",
      assignee: "Mike Chen",
      dueDate: daysAgo(-4),
    },
  },
  {
    id: "act-16",
    type: "file",
    user: mike,
    timestamp: daysAgo(1, 6),
    description: "Renamed Column.tsx",
    file: {
      operation: "renamed",
      path: "src/board/BoardColumn.tsx",
      previousPath: "src/board/Column.tsx",
    },
  },
  {
    id: "act-17",
    type: "commit",
    user: sarah,
    timestamp: daysAgo(1, 7),
    description: "Tighten focus ring contrast on inputs",
    commit: {
      message: "Tighten focus ring contrast on inputs",
      hash: "e5f6071",
      branch: "fix/a11y-focus",
      additions: 36,
      deletions: 22,
      files: [
        { path: "src/styles/app.css", additions: 18, deletions: 12 },
        { path: "src/components/Input/Input.tsx", additions: 18, deletions: 10 },
      ],
    },
  },
  {
    id: "act-18",
    type: "pr",
    user: sarah,
    timestamp: daysAgo(1, 8),
    description: "Opened PR #291 Improve focus visibility",
    pr: {
      action: "Opened PR #291",
      number: 291,
      title: "Improve focus visibility",
      status: "open",
      reviewers: ["Emma Davis", "Priya Nair"],
    },
  },
  {
    id: "act-19",
    type: "commit",
    user: john,
    timestamp: daysAgo(2, 1),
    description: "Implement dark mode toggle component",
    commit: {
      message: "Implement dark mode toggle component",
      hash: "d4e5f6g",
      branch: "feature/dark-mode",
      additions: 234,
      deletions: 12,
      files: [
        { path: "src/components/ThemeToggle/ThemeToggle.tsx", additions: 96, deletions: 0 },
        { path: "src/providers/ThemeProvider.tsx", additions: 58, deletions: 6 },
        { path: "src/styles/themes.css", additions: 44, deletions: 2 },
        { path: "src/components/Header/Header.tsx", additions: 21, deletions: 4 },
        { path: "src/hooks/useMediaQuery.ts", additions: 15, deletions: 0 },
      ],
    },
  },
  {
    id: "act-20",
    type: "file",
    user: sarah,
    timestamp: daysAgo(2, 3),
    description: "Created Dashboard.tsx",
    file: {
      operation: "created",
      path: "src/pages/Dashboard/Dashboard.tsx",
      size: "2.5 KB",
    },
  },
  {
    id: "act-21",
    type: "comment",
    user: emma,
    timestamp: daysAgo(2, 4),
    description: "Commented on ThemeToggle.tsx",
    comment: {
      target: "ThemeToggle.tsx",
      line: 31,
      text: "Can we announce the theme change to screen readers? Right now the switch flips silently, which is confusing when the visual change isn't perceivable.",
      replies: [],
    },
  },
  {
    id: "act-22",
    type: "task",
    user: john,
    timestamp: daysAgo(2, 5),
    description: "Completed Add theme toggle to header",
    task: {
      key: "TASK-118",
      title: "Add theme toggle to header",
      action: "completed",
      status: "completed",
      priority: "high",
      assignee: "John Doe",
      dueDate: daysAgo(2, 5),
    },
  },
  {
    id: "act-23",
    type: "settings",
    user: priya,
    timestamp: daysAgo(2, 6),
    description: "Changed Default Theme",
    settings: {
      name: "Default Theme",
      before: "Light",
      after: "System",
      scope: "Workspace",
    },
  },
  {
    id: "act-24",
    type: "commit",
    user: tom,
    timestamp: daysAgo(2, 8),
    description: "Add skeleton loaders to dashboard cards",
    commit: {
      message: "Add skeleton loaders to dashboard cards",
      hash: "f60718a",
      branch: "feature/dashboard",
      additions: 72,
      deletions: 5,
      files: [
        { path: "src/pages/Dashboard/Skeleton.tsx", additions: 48, deletions: 0 },
        { path: "src/pages/Dashboard/Dashboard.tsx", additions: 24, deletions: 5 },
      ],
    },
  },
  {
    id: "act-25",
    type: "branch",
    user: mike,
    timestamp: daysAgo(3, 1),
    description: "Created branch feature/new-dashboard",
    branch: { action: "Created branch", branch: "feature/new-dashboard" },
  },
  {
    id: "act-26",
    type: "commit",
    user: mike,
    timestamp: daysAgo(3, 2),
    description: "Scaffold new dashboard layout",
    commit: {
      message: "Scaffold new dashboard layout",
      hash: "0718a2b",
      branch: "feature/new-dashboard",
      additions: 196,
      deletions: 0,
      files: [
        { path: "src/pages/Dashboard/DashboardLayout.tsx", additions: 112, deletions: 0 },
        { path: "src/pages/Dashboard/widgets/Widget.tsx", additions: 84, deletions: 0 },
      ],
    },
  },
  {
    id: "act-27",
    type: "comment",
    user: sarah,
    timestamp: daysAgo(3, 3),
    description: "Commented on DashboardLayout.tsx",
    comment: {
      target: "DashboardLayout.tsx",
      line: 64,
      text: "The grid collapses to one column below 900px, which leaves a lot of dead space on tablets. Two columns down to 640px reads better with the current card sizes.",
      replies: [
        {
          author: "Mike Chen",
          text: "Will adjust the breakpoint.",
          timestamp: daysAgo(3, 2.5),
        },
        {
          author: "Emma Davis",
          text: "Please check it against the tablet mock too.",
          timestamp: daysAgo(3, 2.1),
        },
      ],
    },
  },
  {
    id: "act-28",
    type: "task",
    user: emma,
    timestamp: daysAgo(3, 5),
    description: "Created Responsive audit for dashboard",
    task: {
      key: "TASK-129",
      title: "Responsive audit for dashboard",
      action: "created",
      status: "created",
      priority: "medium",
      assignee: "Priya Nair",
      dueDate: daysAgo(-6),
    },
  },
  {
    id: "act-29",
    type: "file",
    user: john,
    timestamp: daysAgo(3, 7),
    description: "Deleted LegacyDashboard.tsx",
    file: {
      operation: "deleted",
      path: "src/pages/Dashboard/LegacyDashboard.tsx",
    },
  },
  {
    id: "act-30",
    type: "pr",
    user: emma,
    timestamp: daysAgo(4, 2),
    description: "Merged PR #284 Add user authentication",
    pr: {
      action: "Merged PR #284",
      number: 284,
      title: "Add user authentication",
      status: "merged",
      reviewers: ["John Doe", "Sarah Johnson"],
    },
  },
  {
    id: "act-31",
    type: "commit",
    user: emma,
    timestamp: daysAgo(4, 3),
    description: "Merge branch feature/auth into main",
    commit: {
      message: "Merge branch feature/auth into main",
      hash: "18a2b3c",
      branch: "main",
      additions: 412,
      deletions: 96,
      files: [
        { path: "src/api/auth.ts", additions: 128, deletions: 22 },
        { path: "src/providers/SessionProvider.tsx", additions: 96, deletions: 14 },
        { path: "src/pages/Login/Login.tsx", additions: 88, deletions: 34 },
        { path: "src/routes/guards.ts", additions: 62, deletions: 18 },
        { path: "src/utils/token.ts", additions: 38, deletions: 8 },
      ],
    },
  },
  {
    id: "act-32",
    type: "user",
    user: priya,
    timestamp: daysAgo(4, 5),
    description: "Priya Nair joined the project",
    userEvent: { action: "joined the project" },
  },
  {
    id: "act-33",
    type: "settings",
    user: john,
    timestamp: daysAgo(4, 7),
    description: "Changed Branch Protection",
    settings: {
      name: "Branch Protection",
      before: "1 approval",
      after: "2 approvals",
      scope: "main",
    },
  },
  {
    id: "act-34",
    type: "task",
    user: tom,
    timestamp: daysAgo(5, 1),
    description: "Created Fix navigation bug on mobile",
    task: {
      key: "TASK-124",
      title: "Fix navigation bug on mobile",
      action: "created",
      status: "created",
      priority: "high",
      assignee: "John Doe",
      dueDate: daysAgo(-9),
    },
  },
  {
    id: "act-35",
    type: "commit",
    user: john,
    timestamp: daysAgo(5, 3),
    description: "Fix mobile nav drawer trapping scroll",
    commit: {
      message: "Fix mobile nav drawer trapping scroll",
      hash: "a2b3c4d",
      branch: "fix/mobile-nav",
      additions: 58,
      deletions: 31,
      files: [
        { path: "src/components/NavDrawer/NavDrawer.tsx", additions: 42, deletions: 26 },
        { path: "src/hooks/useLockBodyScroll.ts", additions: 16, deletions: 5 },
      ],
    },
  },
  {
    id: "act-36",
    type: "comment",
    user: mike,
    timestamp: daysAgo(5, 5),
    description: "Commented on NavDrawer.tsx",
    comment: {
      target: "NavDrawer.tsx",
      line: 88,
      text: "Body scroll lock works, but focus still escapes the drawer on tab. Worth wiring the same focus trap the dialog uses instead of a second implementation.",
      replies: [
        {
          author: "John Doe",
          text: "Reusing the dialog trap — much less code.",
          timestamp: daysAgo(5, 4.2),
        },
      ],
    },
  },
  {
    id: "act-37",
    type: "file",
    user: priya,
    timestamp: daysAgo(5, 8),
    description: "Created useFocusTrap.ts",
    file: {
      operation: "created",
      path: "src/hooks/useFocusTrap.ts",
      size: "1.8 KB",
    },
  },
  {
    id: "act-38",
    type: "branch",
    user: sarah,
    timestamp: daysAgo(6, 2),
    description: "Created branch feature/activity-timeline",
    branch: { action: "Created branch", branch: "feature/activity-timeline" },
  },
  {
    id: "act-39",
    type: "commit",
    user: sarah,
    timestamp: daysAgo(6, 3),
    description: "Add activity timeline data model",
    commit: {
      message: "Add activity timeline data model",
      hash: "b3c4d5e",
      branch: "feature/activity-timeline",
      additions: 148,
      deletions: 0,
      files: [
        { path: "src/domain/activity/activity.ts", additions: 92, deletions: 0 },
        { path: "src/domain/activity/index.ts", additions: 2, deletions: 0 },
        { path: "src/domain/activity/activity.mock.ts", additions: 54, deletions: 0 },
      ],
    },
  },
  {
    id: "act-40",
    type: "task",
    user: sarah,
    timestamp: daysAgo(6, 5),
    description: "Updated Design activity timeline page",
    task: {
      key: "TASK-131",
      title: "Design activity timeline page",
      action: "updated",
      status: "in-progress",
      priority: "high",
      assignee: "Sarah Johnson",
      dueDate: daysAgo(-3),
    },
  },
  {
    id: "act-41",
    type: "settings",
    user: emma,
    timestamp: daysAgo(6, 7),
    description: "Changed Notification Digest",
    settings: {
      name: "Notification Digest",
      before: "Instant",
      after: "Daily",
      scope: "Project",
    },
  },
  {
    id: "act-42",
    type: "commit",
    user: priya,
    timestamp: daysAgo(7, 2),
    description: "Add keyboard shortcuts help dialog",
    commit: {
      message: "Add keyboard shortcuts help dialog",
      hash: "c4d5e6f",
      branch: "feature/shortcuts",
      additions: 118,
      deletions: 6,
      files: [
        { path: "src/components/ShortcutsDialog/ShortcutsDialog.tsx", additions: 92, deletions: 0 },
        { path: "src/app/root.tsx", additions: 26, deletions: 6 },
      ],
    },
  },
  {
    id: "act-43",
    type: "comment",
    user: tom,
    timestamp: daysAgo(7, 4),
    description: "Commented on ShortcutsDialog.tsx",
    comment: {
      target: "ShortcutsDialog.tsx",
      line: 12,
      text: "Shortcut list is hardcoded here and also in the board view. If we pull it into a constants file the two can't drift apart.",
      replies: [],
    },
  },
  {
    id: "act-44",
    type: "task",
    user: mike,
    timestamp: daysAgo(8, 3),
    description: "Completed Extract shortcut constants",
    task: {
      key: "TASK-127",
      title: "Extract shortcut constants",
      action: "completed",
      status: "completed",
      priority: "low",
      assignee: "Mike Chen",
      dueDate: daysAgo(8, 3),
    },
  },
  {
    id: "act-45",
    type: "pr",
    user: john,
    timestamp: daysAgo(8, 6),
    description: "Merged PR #279 Board drag and drop polish",
    pr: {
      action: "Merged PR #279",
      number: 279,
      title: "Board drag and drop polish",
      status: "merged",
      reviewers: ["Mike Chen", "Emma Davis"],
    },
  },
  {
    id: "act-46",
    type: "file",
    user: emma,
    timestamp: daysAgo(9, 4),
    description: "Created ShortcutList.const.ts",
    file: {
      operation: "created",
      path: "src/constants/ShortcutList.const.ts",
      size: "0.9 KB",
    },
  },
  {
    id: "act-47",
    type: "commit",
    user: tom,
    timestamp: daysAgo(10, 2),
    description: "Replace inline SVGs with icon components",
    commit: {
      message: "Replace inline SVGs with icon components",
      hash: "d5e6f70",
      branch: "chore/icons",
      additions: 204,
      deletions: 268,
      files: [
        { path: "src/components/Icons/Icons.tsx", additions: 148, deletions: 0 },
        { path: "src/components/Header/Header.tsx", additions: 28, deletions: 132 },
        { path: "src/board/BoardColumn.tsx", additions: 28, deletions: 136 },
      ],
    },
  },
  {
    id: "act-48",
    type: "user",
    user: mike,
    timestamp: daysAgo(11, 5),
    description: "Mike Chen was assigned as reviewer",
    userEvent: { action: "assigned as reviewer on chore/icons" },
  },
  {
    id: "act-49",
    type: "settings",
    user: john,
    timestamp: daysAgo(12, 3),
    description: "Changed Issue Auto-Assign",
    settings: {
      name: "Issue Auto-Assign",
      before: "Off",
      after: "Round robin",
      scope: "Project",
    },
  },
  {
    id: "act-50",
    type: "task",
    user: priya,
    timestamp: daysAgo(14, 2),
    description: "Created Add empty states to every list view",
    task: {
      key: "TASK-115",
      title: "Add empty states to every list view",
      action: "created",
      status: "created",
      priority: "medium",
      assignee: "Tom Wilson",
      dueDate: daysAgo(-1),
    },
  },
  {
    id: "act-51",
    type: "commit",
    user: sarah,
    timestamp: daysAgo(16, 6),
    description: "Add empty state illustrations",
    commit: {
      message: "Add empty state illustrations",
      hash: "e6f7081",
      branch: "feature/empty-states",
      additions: 132,
      deletions: 14,
      files: [
        { path: "src/components/EmptyState/EmptyState.tsx", additions: 86, deletions: 0 },
        { path: "src/pages/Projects/Projects.tsx", additions: 46, deletions: 14 },
      ],
    },
  },
  {
    id: "act-52",
    type: "branch",
    user: emma,
    timestamp: daysAgo(19, 3),
    description: "Created branch feature/empty-states",
    branch: { action: "Created branch", branch: "feature/empty-states" },
  },
  {
    id: "act-53",
    type: "file",
    user: mike,
    timestamp: daysAgo(22, 5),
    description: "Renamed Projects.tsx",
    file: {
      operation: "renamed",
      path: "src/pages/Projects/ProjectsPage.tsx",
      previousPath: "src/pages/Projects/Projects.tsx",
    },
  },
  {
    id: "act-54",
    type: "pr",
    user: tom,
    timestamp: daysAgo(25, 4),
    description: "Closed PR #262 Experimental gantt view",
    pr: {
      action: "Closed PR #262",
      number: 262,
      title: "Experimental gantt view",
      status: "closed",
      reviewers: ["John Doe"],
    },
  },
  {
    id: "act-55",
    type: "user",
    user: john,
    timestamp: daysAgo(28, 6),
    description: "John Doe created the project",
    userEvent: { action: "created the project" },
  },
];
