import type { Meta, StoryObj } from "@storybook/react-vite";
import { KpiBuilder } from "./kpi-builder";
import { createSubKpi, KpiFormData } from "./kpi-builder.types";

const meta: Meta<typeof KpiBuilder> = {
  title: "Pages/Main/Project/Analytics/KpiBuilder",
  component: KpiBuilder,
  parameters: {
    layout: "fullscreen",
  },
  decorators: [
    (Story) => (
      <div className="min-h-screen bg-elevation-surface" style={{ minWidth: 1200 }}>
        <Story />
      </div>
    ),
  ],
};

export default meta;
type Story = StoryObj<typeof KpiBuilder>;

const DESCRIPTION =
  "Tracking customer retention is crucial for understanding our business health. Each quarter, we should analyze the percentage of customers we lose. This metric will help us identify trends and areas for improvement. By monitoring these numbers closely, we can implement strategies to enhance customer satisfaction. Additionally, we can compare our quarterly losses to industry standards. This will give us a clearer picture of our performance. Understanding why customers leave is just as important as knowing how many.";

// ── Build the auto-generated sub-KPI tree ────────────────────────────────
function buildGeneratedTree(): KpiFormData {
  const cancelledSubs = createSubKpi("Cancelled Subscriptions");
  cancelledSubs.aggregationType = "count";
  cancelledSubs.formula = "COUNT(SubscriptionID) WHERE Event = 'Cancel'";
  cancelledSubs.conditions = "Event = 'Cancel' AND Period = QUARTER";
  cancelledSubs.example = "780 cancelled subscriptions";

  const nonRenewals = createSubKpi("Non-Renewals");
  nonRenewals.aggregationType = "count";
  nonRenewals.formula = "COUNT(CustomerID) WHERE RenewalDate < NOW() AND Status != 'Active'";
  nonRenewals.conditions = "RenewalDate < NOW() AND Status != 'Active'";
  nonRenewals.example = "220 non-renewals";

  const grossChurned = createSubKpi("Total Churned Customers");
  grossChurned.aggregationType = "count";
  grossChurned.formula = "COUNT(CustomerID) WHERE Status = 'Churned'";
  grossChurned.conditions = "Status = 'Churned' AND Period = QUARTER";
  grossChurned.example = "1 000 customers churned this quarter";
  grossChurned.subKpis = [cancelledSubs, nonRenewals];

  const startCustomers = createSubKpi("Starting Customer Count");
  startCustomers.aggregationType = "count";
  startCustomers.formula = "COUNT(CustomerID) WHERE Period_Start = TRUE";
  startCustomers.conditions = "Period_Start = TRUE";
  startCustomers.example = "12 500 customers at start of quarter";

  return {
    name: "Customer Churn Rate",
    tooltipText: "Measures customer attrition as a percentage",
    description: DESCRIPTION,
    aggregationType: "ratio",
    formula: "( Total Churned Customers / Starting Customer Count ) × 100",
    conditions: "Period = QUARTER AND CustomerType = 'Paying'",
    example: "( 1 000 / 12 500 ) × 100 = 8%",
    subKpis: [grossChurned, startCustomers],
  };
}

/** 1️⃣  Idle — user has not yet clicked Generate */
export const Default: Story = {
  args: {
    initialForm: {
      name: "Customer Churn Rate",
      tooltipText: "Measures customer attrition as a percentage",
      description: "",
      aggregationType: "count",
      formula: "",
      conditions: "",
      example: "",
      subKpis: [],
    },
    initialGenerationState: "idle",
  },
};

/** 2️⃣  Generating — AI is working, skeletons visible */
export const Generating: Story = {
  args: {
    initialForm: {
      name: "Customer Churn Rate",
      tooltipText: "Measures customer attrition as a percentage",
      description: DESCRIPTION,
      aggregationType: "count",
      formula: "",
      conditions: "",
      example: "",
      subKpis: [],
    },
    initialGenerationState: "generating",
  },
};

/** 3️⃣  Done — auto-generated tree with nested sub-KPIs */
export const WithAutoGeneratedSubKpis: Story = {
  args: {
    initialForm: buildGeneratedTree(),
    initialGenerationState: "done",
  },
};
